### ISSUE TITLE
Problems finding CKann extension

### ISSUE THREAD

**Issue by chmanie** [go-e/annotator#5]
I reinstalled GoE freshly on an existing server (chmanie1) using `scripts/reinstall_goe chmanie1` and after that I got the following error message on an essence page:

```
Uncaught ReferenceError: PageTextMapperCore is not defined(anonymous function) @ ckann-all.js:18004(anonymous function) @ ckann-all.js:18125
ann.js:310 Uncaught TypeError: Annotator.CKann is not a function
```

@csillag thinks it's the #3 that broke it.

**Comment by scharf** [comment]
I make a quick fix and pushed it.

**Comment by csillag** [comment]
As I wrote [here](https://github.com/go-e/ann/commit/418a43ea33ce925fef892ae6c3d5d85f7fdc194a#commitcomment-13211997), I am not sure the fix is complete, so I am reopening this.

So, here is a list of files removed in https://github.com/go-e/annotator/pull/3:
 - `dom_text_mapper.js`
 - `dom_text_matcher.js`
 - `page_text_mapper_core.js`
 - `text_match_engines.js`

All of these (stale, generated) JS files were found in `ann/lib/vendor`, and now
they are no more. The freshly generated version of all 4 files can be found in `ann/lib/vendor/src`.

Checking the [latest version of the Makefile](https://github.com/go-e/ann/blob/418a43ea33ce925fef892ae6c3d5d85f7fdc194a/ann/Makefile), I see valid references to the new locations for 3 of the 4 files, but not the forth. I think that needs to be fixed, too.

**Comment by scharf** [comment]
I see all 4 of them https://github.com/go-e/ann/blob/418a43ea33ce925fef892ae6c3d5d85f7fdc194a/ann/Makefile#L27-L30

**Comment by scharf** [comment]
I use the same order of the files as in https://github.com/go-e/annotator/blob/fa06185b79585c3ec103a1fbc24d0cf969e9ce0e/test/runner.html#L18-L21

**Comment by csillag** [comment]
> I see all 4 of them [here](https://github.com/go-e/ann/blob/418a43ea33ce925fef892ae6c3d5d85f7fdc194a/ann/Makefile#L27-L30).

Oh, I see, they are indeed all there. What misled me is that in the previous version, we had two instances of the `text_match_engines` JS, a few lines apart: [here](https://github.com/go-e/ann/blob/280d00dde0285eef3b07ac57a87df2dccf22e929/ann/Makefile#L26) and [here](https://github.com/go-e/ann/blob/280d00dde0285eef3b07ac57a87df2dccf22e929/ann/Makefile#L32).

Therefore, in your change, you only removed the wrong one, but didn't add anything, and so I wrongly assumed that it's missing now. 

All cleared  up, thank you. Closing again.
